name: Lab 3 - Parallel jobs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test-validator:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: ./lab3
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
            cd lab3
            pip install -r requirements.txt
     
      - name: Run test_validator
        
        run: |
         pwd
         cd lab3
         pytest test_validator.py -v

