name: Lab 3 - Parallel jobs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run ${{ matrix.test_name }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lab3

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: validator
            test_file: test_validator.py
          - test_name: transformer
            test_file: test_transformer.py
          - test_name: reporter
            test_file: test_reporter.py

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest ${{ matrix.test_file }} -v

  pipeline-summary:
    runs-on: ubuntu-latest
    needs: tests
    if: always()

    steps:
      - name: Print summary
        run: |
          echo "All matrix test jobs finished."
          echo "Tests result: ${{ needs.tests.result }}"